/**
 * Match Sheet / Player List PDF generation (V1).
 *
 * Architecture rules (see brief):
 *  - Server-side only. The caller MUST be authorized as a coach/admin of the
 *    event's team via the existing `is_team_coach` RPC. We never trust the UI.
 *  - PII surface is intentionally minimal: jersey, first/last name, birth date,
 *    license number — and only for convocated players of THIS event's team.
 *  - Every successful generation is written to `audit_logs`.
 *  - Service-role admin client is used for the read because RLS already restricts
 *    what `is_team_coach` allows; we never widen the column set beyond what is
 *    on the brief.
 *  - SVG club logos are rejected (no raw embed — XSS hardening parity with the
 *    public roster logo upload).
 */
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFImage } from "pdf-lib";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { sortConvocatedPlayers, type MatchSheetPlayer } from "./sort";

export type MatchSheetLang = "fr" | "en" | "de" | "es" | "it" | "nl" | "pt";

interface I18nStrings {
  titleMatch: string;
  titleTournament: string;
  typeMatch: string;
  typeTournament: string;
  date: string;
  time: string;
  location: string;
  opponent: string;
  team: string;
  club: string;
  jersey: string;
  lastName: string;
  firstName: string;
  birthDate: string;
  license: string;
  generatedBy: string;
  eventId: string;
  noPlayers: string;
}

const STRINGS: Record<MatchSheetLang, I18nStrings> = {
  fr: {
    titleMatch: "Feuille de match",
    titleTournament: "Liste des joueurs",
    typeMatch: "Match",
    typeTournament: "Tournoi",
    date: "Date",
    time: "Heure",
    location: "Lieu",
    opponent: "Adversaire",
    team: "Équipe",
    club: "Club",
    jersey: "Maillot",
    lastName: "Nom",
    firstName: "Prénom",
    birthDate: "Date de naissance",
    license: "N° de licence",
    generatedBy: "Généré par Clubero",
    eventId: "Event ID",
    noPlayers: "Aucun joueur convoqué",
  },
  en: {
    titleMatch: "Match sheet",
    titleTournament: "Player list",
    typeMatch: "Match",
    typeTournament: "Tournament",
    date: "Date",
    time: "Time",
    location: "Venue",
    opponent: "Opponent",
    team: "Team",
    club: "Club",
    jersey: "Jersey",
    lastName: "Last name",
    firstName: "First name",
    birthDate: "Date of birth",
    license: "License #",
    generatedBy: "Generated by Clubero",
    eventId: "Event ID",
    noPlayers: "No players called up",
  },
  de: {
    titleMatch: "Spielbericht",
    titleTournament: "Spielerliste",
    typeMatch: "Spiel",
    typeTournament: "Turnier",
    date: "Datum",
    time: "Uhrzeit",
    location: "Ort",
    opponent: "Gegner",
    team: "Mannschaft",
    club: "Verein",
    jersey: "Trikot",
    lastName: "Nachname",
    firstName: "Vorname",
    birthDate: "Geburtsdatum",
    license: "Lizenz-Nr.",
    generatedBy: "Erstellt von Clubero",
    eventId: "Event-ID",
    noPlayers: "Keine Spieler einberufen",
  },
  es: {
    titleMatch: "Acta de partido",
    titleTournament: "Lista de jugadores",
    typeMatch: "Partido",
    typeTournament: "Torneo",
    date: "Fecha",
    time: "Hora",
    location: "Lugar",
    opponent: "Rival",
    team: "Equipo",
    club: "Club",
    jersey: "Dorsal",
    lastName: "Apellido",
    firstName: "Nombre",
    birthDate: "Fecha de nacimiento",
    license: "N.º de licencia",
    generatedBy: "Generado por Clubero",
    eventId: "ID del evento",
    noPlayers: "Ningún jugador convocado",
  },
  it: {
    titleMatch: "Distinta di gara",
    titleTournament: "Elenco giocatori",
    typeMatch: "Partita",
    typeTournament: "Torneo",
    date: "Data",
    time: "Ora",
    location: "Luogo",
    opponent: "Avversario",
    team: "Squadra",
    club: "Club",
    jersey: "Maglia",
    lastName: "Cognome",
    firstName: "Nome",
    birthDate: "Data di nascita",
    license: "N. tessera",
    generatedBy: "Generato da Clubero",
    eventId: "ID evento",
    noPlayers: "Nessun giocatore convocato",
  },
  nl: {
    titleMatch: "Wedstrijdformulier",
    titleTournament: "Spelerslijst",
    typeMatch: "Wedstrijd",
    typeTournament: "Toernooi",
    date: "Datum",
    time: "Tijd",
    location: "Locatie",
    opponent: "Tegenstander",
    team: "Team",
    club: "Club",
    jersey: "Rugnr.",
    lastName: "Achternaam",
    firstName: "Voornaam",
    birthDate: "Geboortedatum",
    license: "Licentienr.",
    generatedBy: "Gegenereerd door Clubero",
    eventId: "Event-ID",
    noPlayers: "Geen spelers opgeroepen",
  },
  pt: {
    titleMatch: "Ficha de jogo",
    titleTournament: "Lista de jogadores",
    typeMatch: "Jogo",
    typeTournament: "Torneio",
    date: "Data",
    time: "Hora",
    location: "Local",
    opponent: "Adversário",
    team: "Equipa",
    club: "Clube",
    jersey: "Camisola",
    lastName: "Apelido",
    firstName: "Nome",
    birthDate: "Data de nascimento",
    license: "Nº de licença",
    generatedBy: "Gerado pelo Clubero",
    eventId: "ID do evento",
    noPlayers: "Nenhum jogador convocado",
  },
};

export function pickLang(raw: string | undefined | null): MatchSheetLang {
  const v = (raw ?? "").toLowerCase().slice(0, 2);
  if (v === "fr" || v === "en" || v === "de" || v === "es" || v === "it" || v === "nl" || v === "pt") return v;
  return "en";
}

// Helvetica WinAnsi already covers Latin-1 accents (é, è, à, ç, ü, ö, ñ, ã).
// Strip only chars outside that range; never throw.
function safe(s: string | null | undefined): string {
  const v = (s ?? "").toString();
  return v
    .replace(/[\u2212\u2012\u2013\u2014\u2015]/g, "-")
    .replace(/[\u2018\u2019\u201A\u201B]/g, "'")
    .replace(/[\u201C\u201D\u201E\u201F]/g, '"')
    .replace(/\u2026/g, "...")
    .replace(/\u00A0/g, " ")
    .replace(/[^\x20-\x7E\u00A0-\u00FF]/g, "?");
}

function fmtDate(iso: string | null | undefined, lang: MatchSheetLang): string {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return "—";
  const locale =
    lang === "fr"
      ? "fr-FR"
      : lang === "de"
        ? "de-DE"
        : lang === "es"
          ? "es-ES"
          : lang === "it"
            ? "it-IT"
            : lang === "nl"
              ? "nl-NL"
              : lang === "pt"
                ? "pt-PT"
                : "en-GB";
  return d.toLocaleDateString(locale, { day: "2-digit", month: "long", year: "numeric" });
}

function fmtTime(iso: string | null | undefined): string {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return "—";
  return d.toISOString().slice(11, 16) + " UTC";
}

function fmtBirth(iso: string | null | undefined, lang: MatchSheetLang): string {
  if (!iso) return "—";
  // birth_date stored as a date — render as locale short
  return fmtDate(iso, lang);
}

interface LogoBytes {
  bytes: ArrayBuffer;
  kind: "png" | "jpg";
}

/**
 * Fetch a remote image and classify it. SVG is REJECTED (returns null) to
 * avoid embedding untrusted XML; matches the public roster logo policy.
 */
async function fetchImage(url: string): Promise<LogoBytes | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const ct = (res.headers.get("content-type") ?? "").toLowerCase();
    if (ct.includes("svg") || url.toLowerCase().endsWith(".svg")) return null;
    const bytes = await res.arrayBuffer();
    if (ct.includes("png") || url.toLowerCase().endsWith(".png")) return { bytes, kind: "png" };
    return { bytes, kind: "jpg" };
  } catch {
    return null;
  }
}

async function embedLogo(doc: PDFDocument, logo: LogoBytes | null): Promise<PDFImage | null> {
  if (!logo) return null;
  try {
    return logo.kind === "png" ? await doc.embedPng(logo.bytes) : await doc.embedJpg(logo.bytes);
  } catch {
    return null;
  }
}

export interface MatchSheetEvent {
  id: string;
  type: "match" | "tournament" | string;
  title: string | null;
  starts_at: string | null;
  location: string | null;
  opponent: string | null;
  team_id: string;
}

export interface MatchSheetInputs {
  event: MatchSheetEvent;
  clubName: string | null;
  teamName: string | null;
  clubLogoUrl: string | null;
  players: readonly MatchSheetPlayer[];
  lang: MatchSheetLang;
}

export async function buildMatchSheetPdf(inputs: MatchSheetInputs): Promise<Uint8Array> {
  const { event, clubName, teamName, clubLogoUrl, players, lang } = inputs;
  const t = STRINGS[lang];
  const isTournament = event.type === "tournament";
  const title = isTournament ? t.titleTournament : t.titleMatch;
  const typeLabel = isTournament ? t.typeTournament : t.typeMatch;

  const doc = await PDFDocument.create();
  doc.setTitle(`${title} — ${event.title ?? ""}`.trim());
  doc.setCreator("Clubero");

  const page = doc.addPage([595.28, 841.89]); // A4 portrait
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const ink = rgb(0.06, 0.09, 0.16);
  const muted = rgb(0.39, 0.45, 0.55);
  const stripe = rgb(0.965, 0.965, 0.97);
  const accent = rgb(0.11, 0.34, 0.82);

  const W = 595.28;
  const H = 841.89;
  const ML = 40;
  const MR = 40;
  let y = H - 50;

  // ── Header band ─────────────────────────────────────────────
  page.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: accent });
  page.drawText(safe(title), {
    x: ML,
    y: H - 35,
    size: 20,
    font: bold,
    color: rgb(1, 1, 1),
  });
  page.drawText(safe(typeLabel + (event.title ? " — " + event.title : "")), {
    x: ML,
    y: H - 58,
    size: 11,
    font,
    color: rgb(1, 1, 1),
  });

  // Optional club logo (top-right, safely embedded — SVG rejected upstream).
  const clubLogo = clubLogoUrl ? await fetchImage(clubLogoUrl) : null;
  const clubLogoImg = await embedLogo(doc, clubLogo);
  if (clubLogoImg) {
    const max = 50;
    const ratio = Math.min(max / clubLogoImg.width, max / clubLogoImg.height);
    const w = clubLogoImg.width * ratio;
    const h = clubLogoImg.height * ratio;
    page.drawImage(clubLogoImg, { x: W - MR - w, y: H - 15 - h, width: w, height: h });
  }

  y = H - 110;

  // ── Meta block ──────────────────────────────────────────────
  const meta: Array<[string, string]> = [];
  if (clubName) meta.push([t.club, clubName]);
  if (teamName) meta.push([t.team, teamName]);
  meta.push([t.date, fmtDate(event.starts_at, lang)]);
  meta.push([t.time, fmtTime(event.starts_at)]);
  if (event.location) meta.push([t.location, event.location]);
  if (!isTournament && event.opponent) meta.push([t.opponent, event.opponent]);

  for (const [k, v] of meta) {
    page.drawText(safe(k) + ":", { x: ML, y, size: 10, font, color: muted });
    page.drawText(safe(v), { x: ML + 130, y, size: 10, font: bold, color: ink });
    y -= 16;
  }

  y -= 10;

  // ── Table header ────────────────────────────────────────────
  const cols = [
    { key: "jersey", label: t.jersey, x: ML, w: 50, align: "center" as const },
    { key: "last", label: t.lastName, x: ML + 50, w: 130, align: "left" as const },
    { key: "first", label: t.firstName, x: ML + 180, w: 110, align: "left" as const },
    { key: "birth", label: t.birthDate, x: ML + 290, w: 110, align: "left" as const },
    { key: "license", label: t.license, x: ML + 400, w: 115, align: "left" as const },
  ];

  const tableW = W - ML - MR;
  page.drawRectangle({ x: ML, y: y - 4, width: tableW, height: 22, color: ink });
  for (const c of cols) {
    const label = safe(c.label);
    const tx =
      c.align === "center" ? c.x + c.w / 2 - bold.widthOfTextAtSize(label, 9) / 2 : c.x + 6;
    page.drawText(label, { x: tx, y: y + 4, size: 9, font: bold, color: rgb(1, 1, 1) });
  }
  y -= 24;

  // ── Rows ────────────────────────────────────────────────────
  const sorted = sortConvocatedPlayers(players);
  if (sorted.length === 0) {
    page.drawText(safe(t.noPlayers), { x: ML, y, size: 11, font, color: muted });
    y -= 18;
  } else {
    for (let i = 0; i < sorted.length; i++) {
      const p = sorted[i];
      if (y < 70) {
        // continue on a new page if we ever overflow A4
        const np = doc.addPage([W, H]);
        np.drawText(safe(title) + " (suite)", { x: ML, y: H - 40, size: 12, font: bold, color: ink });
        y = H - 70;
      }
      if (i % 2 === 1) {
        page.drawRectangle({ x: ML, y: y - 4, width: tableW, height: 18, color: stripe });
      }
      const jersey = typeof p.jersey_number === "number" ? String(p.jersey_number) : "—";
      const cells: Record<string, string> = {
        jersey,
        last: safe(p.last_name) || "—",
        first: safe(p.first_name) || "—",
        birth: fmtBirth(p.birth_date, lang),
        license: safe(p.license_number) || "—",
      };
      for (const c of cols) {
        const v = cells[c.key] ?? "—";
        const tx =
          c.align === "center" ? c.x + c.w / 2 - font.widthOfTextAtSize(v, 10) / 2 : c.x + 6;
        page.drawText(v, { x: tx, y: y + 2, size: 10, font, color: ink });
      }
      y -= 18;
    }
  }

  drawFooter(page, font, muted, t, event.id, W, ML, MR);
  return await doc.save();
}

function drawFooter(
  page: ReturnType<PDFDocument["addPage"]>,
  font: PDFFont,
  muted: ReturnType<typeof rgb>,
  t: I18nStrings,
  eventId: string,
  W: number,
  ML: number,
  _MR: number,
) {
  const now = new Date();
  const stamp =
    String(now.getUTCDate()).padStart(2, "0") +
    "/" +
    String(now.getUTCMonth() + 1).padStart(2, "0") +
    "/" +
    now.getUTCFullYear() +
    " " +
    String(now.getUTCHours()).padStart(2, "0") +
    ":" +
    String(now.getUTCMinutes()).padStart(2, "0") +
    " UTC";
  page.drawText(safe(t.generatedBy), { x: ML, y: 40, size: 8, font, color: muted });
  page.drawText(stamp, { x: ML, y: 28, size: 8, font, color: muted });
  page.drawText(safe(t.eventId) + ": " + eventId, { x: ML, y: 16, size: 8, font, color: muted });
  void W;
}

// ───────────────────────────────────────────────────────────────
// High-level orchestration: auth + data fetch + audit + PDF build.
// Throws Response(403) when the caller is not authorized.
// ───────────────────────────────────────────────────────────────
export async function generateMatchSheetForUser(opts: {
  eventId: string;
  userId: string;
  lang: MatchSheetLang;
}): Promise<{ bytes: Uint8Array; filename: string }> {
  const { eventId, userId, lang } = opts;

  // 1) Load the event minimally to know its team.
  const { data: ev } = await supabaseAdmin
    .from("events")
    .select("id, type, title, starts_at, location, opponent, team_id")
    .eq("id", eventId)
    .maybeSingle();
  if (!ev?.team_id) throw new Response("Not found", { status: 404 });

  // 2) Authorize: caller must be a coach/admin of the event's team.
  //    Mirrors the lineup-email server flow (also IDOR-safe: the eventId is
  //    used to find the team, and the team is what we check the role against).
  const { data: ok } = await supabaseAdmin.rpc("is_team_coach", {
    _user_id: userId,
    _team_id: ev.team_id,
  });
  if (!ok) throw new Response("Forbidden", { status: 403 });

  // 3) Fetch the team + club for header rendering.
  const { data: team } = await supabaseAdmin
    .from("teams")
    .select("id, name, club_id, clubs:club_id(id, name, logo_url)")
    .eq("id", ev.team_id)
    .maybeSingle();
  const club = (team as { clubs?: { id?: string; name?: string | null; logo_url?: string | null } } | null)
    ?.clubs ?? null;

  // 4) Fetch convocated players for THIS event only.
  //    Brief-restricted columns only — no email / phone / parent data.
  const { data: convs } = await supabaseAdmin
    .from("convocations")
    .select("player_id, players:player_id(id, first_name, last_name, jersey_number, birth_date, license_number)")
    .eq("event_id", eventId);

  const players: MatchSheetPlayer[] = ((convs ?? []) as Array<{ players: MatchSheetPlayer | null }>)
    .map((r) => r.players)
    .filter((p): p is MatchSheetPlayer => !!p);

  // 5) Build the PDF.
  const bytes = await buildMatchSheetPdf({
    event: ev as MatchSheetEvent,
    clubName: club?.name ?? null,
    teamName: (team as { name?: string | null } | null)?.name ?? null,
    clubLogoUrl: club?.logo_url ?? null,
    players,
    lang,
  });

  // 6) Audit log (best-effort — never block the download).
  try {
    await supabaseAdmin.from("audit_logs").insert({
      actor_user_id: userId,
      entity_type: "event",
      entity_id: eventId,
      action: "match_sheet.generated",
      club_id: club?.id ?? null,
      changes: { lang, type: ev.type, player_count: players.length },
    } as never);
  } catch {
    /* never block */
  }

  const slug = (ev.title ?? "match-sheet")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  const filename = `${ev.type === "tournament" ? "joueurs" : "feuille-de-match"}-${slug || eventId.slice(0, 8)}.pdf`;
  return { bytes, filename };
}
