/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DnsCheckRouteImport } from './routes/dns-check'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin/users'
import { Route as SuperadminSupportRouteImport } from './routes/superadmin/support'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin/settings'
import { Route as SuperadminLogsRouteImport } from './routes/superadmin/logs'
import { Route as SuperadminBillingRouteImport } from './routes/superadmin/billing'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as LegalKindRouteImport } from './routes/legal.$kind'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SuperadminClubsIndexRouteImport } from './routes/superadmin/clubs.index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as SuperadminUsersUserIdRouteImport } from './routes/superadmin/users.$userId'
import { Route as SuperadminClubsClubIdRouteImport } from './routes/superadmin/clubs.$clubId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicMarketingChatRouteImport } from './routes/api/public/marketing-chat'
import { Route as ApiPublicInquiryRouteImport } from './routes/api/public/inquiry'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId'
import { Route as AuthenticatedProfilePrivacyRouteImport } from './routes/_authenticated/profile/privacy'
import { Route as AuthenticatedProfilePasswordRouteImport } from './routes/_authenticated/profile/password'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players/$playerId'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events/$eventId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksTrialRemindersRouteImport } from './routes/api/public/hooks/trial-reminders'
import { Route as ApiPublicHooksEventRemindersRouteImport } from './routes/api/public/hooks/event-reminders'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users.$userId'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsCheckRoute = DnsCheckRouteImport.update({
  id: '/dns-check',
  path: '/dns-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSupportRoute = SuperadminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLogsRoute = SuperadminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminBillingRoute = SuperadminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SuperadminRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalKindRoute = LegalKindRouteImport.update({
  id: '/legal/$kind',
  path: '/legal/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SuperadminClubsIndexRoute = SuperadminClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => SuperadminRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const SuperadminUsersUserIdRoute = SuperadminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => SuperadminUsersRoute,
} as any)
const SuperadminClubsClubIdRoute = SuperadminClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => SuperadminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketingChatRoute = ApiPublicMarketingChatRouteImport.update({
  id: '/api/public/marketing-chat',
  path: '/api/public/marketing-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInquiryRoute = ApiPublicInquiryRouteImport.update({
  id: '/api/public/inquiry',
  path: '/api/public/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRoute,
  } as any)
const AuthenticatedProfilePrivacyRoute =
  AuthenticatedProfilePrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfilePasswordRoute =
  AuthenticatedProfilePasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTrialRemindersRoute =
  ApiPublicHooksTrialRemindersRouteImport.update({
    id: '/api/public/hooks/trial-reminders',
    path: '/api/public/hooks/trial-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEventRemindersRoute =
  ApiPublicHooksEventRemindersRouteImport.update({
    id: '/api/public/hooks/event-reminders',
    path: '/api/public/hooks/event-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dns-check': typeof DnsCheckRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/stats': typeof AuthenticatedStatsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/$kind': typeof LegalKindRoute
  '/r/$token': typeof RTokenRoute
  '/superadmin/billing': typeof SuperadminBillingRoute
  '/superadmin/logs': typeof SuperadminLogsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/support': typeof SuperadminSupportRoute
  '/superadmin/users': typeof SuperadminUsersRouteWithChildren
  '/superadmin/': typeof SuperadminIndexRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/marketing-chat': typeof ApiPublicMarketingChatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/superadmin/clubs/$clubId': typeof SuperadminClubsClubIdRoute
  '/superadmin/users/$userId': typeof SuperadminUsersUserIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/superadmin/clubs/': typeof SuperadminClubsIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/event-reminders': typeof ApiPublicHooksEventRemindersRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dns-check': typeof DnsCheckRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/$kind': typeof LegalKindRoute
  '/r/$token': typeof RTokenRoute
  '/superadmin/billing': typeof SuperadminBillingRoute
  '/superadmin/logs': typeof SuperadminLogsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/support': typeof SuperadminSupportRoute
  '/superadmin/users': typeof SuperadminUsersRouteWithChildren
  '/superadmin': typeof SuperadminIndexRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/marketing-chat': typeof ApiPublicMarketingChatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/superadmin/clubs/$clubId': typeof SuperadminClubsClubIdRoute
  '/superadmin/users/$userId': typeof SuperadminUsersUserIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/superadmin/clubs': typeof SuperadminClubsIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/event-reminders': typeof ApiPublicHooksEventRemindersRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dns-check': typeof DnsCheckRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/$kind': typeof LegalKindRoute
  '/r/$token': typeof RTokenRoute
  '/superadmin/billing': typeof SuperadminBillingRoute
  '/superadmin/logs': typeof SuperadminLogsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/support': typeof SuperadminSupportRoute
  '/superadmin/users': typeof SuperadminUsersRouteWithChildren
  '/superadmin/': typeof SuperadminIndexRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/_authenticated/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/_authenticated/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/marketing-chat': typeof ApiPublicMarketingChatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/superadmin/clubs/$clubId': typeof SuperadminClubsClubIdRoute
  '/superadmin/users/$userId': typeof SuperadminUsersUserIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/superadmin/clubs/': typeof SuperadminClubsIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/event-reminders': typeof ApiPublicHooksEventRemindersRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/demo'
    | '/dns-check'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/superadmin'
    | '/admin'
    | '/assistant'
    | '/events'
    | '/follow-ups'
    | '/home'
    | '/inbox'
    | '/profile'
    | '/stats'
    | '/teams'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/legal/$kind'
    | '/r/$token'
    | '/superadmin/billing'
    | '/superadmin/logs'
    | '/superadmin/settings'
    | '/superadmin/support'
    | '/superadmin/users'
    | '/superadmin/'
    | '/admin/billing'
    | '/admin/users'
    | '/events/$eventId'
    | '/players/$playerId'
    | '/profile/password'
    | '/profile/privacy'
    | '/teams/$teamId'
    | '/api/public/inquiry'
    | '/api/public/marketing-chat'
    | '/api/public/stripe-webhook'
    | '/lovable/email/suppression'
    | '/superadmin/clubs/$clubId'
    | '/superadmin/users/$userId'
    | '/admin/'
    | '/profile/'
    | '/superadmin/clubs/'
    | '/admin/users/$userId'
    | '/api/public/hooks/event-reminders'
    | '/api/public/hooks/trial-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/demo'
    | '/dns-check'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/assistant'
    | '/events'
    | '/follow-ups'
    | '/home'
    | '/inbox'
    | '/stats'
    | '/teams'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/legal/$kind'
    | '/r/$token'
    | '/superadmin/billing'
    | '/superadmin/logs'
    | '/superadmin/settings'
    | '/superadmin/support'
    | '/superadmin/users'
    | '/superadmin'
    | '/admin/billing'
    | '/admin/users'
    | '/events/$eventId'
    | '/players/$playerId'
    | '/profile/password'
    | '/profile/privacy'
    | '/teams/$teamId'
    | '/api/public/inquiry'
    | '/api/public/marketing-chat'
    | '/api/public/stripe-webhook'
    | '/lovable/email/suppression'
    | '/superadmin/clubs/$clubId'
    | '/superadmin/users/$userId'
    | '/admin'
    | '/profile'
    | '/superadmin/clubs'
    | '/admin/users/$userId'
    | '/api/public/hooks/event-reminders'
    | '/api/public/hooks/trial-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/demo'
    | '/dns-check'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/superadmin'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/_authenticated/events'
    | '/_authenticated/follow-ups'
    | '/_authenticated/home'
    | '/_authenticated/inbox'
    | '/_authenticated/profile'
    | '/_authenticated/stats'
    | '/_authenticated/teams'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/legal/$kind'
    | '/r/$token'
    | '/superadmin/billing'
    | '/superadmin/logs'
    | '/superadmin/settings'
    | '/superadmin/support'
    | '/superadmin/users'
    | '/superadmin/'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/users'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/players/$playerId'
    | '/_authenticated/profile/password'
    | '/_authenticated/profile/privacy'
    | '/_authenticated/teams/$teamId'
    | '/api/public/inquiry'
    | '/api/public/marketing-chat'
    | '/api/public/stripe-webhook'
    | '/lovable/email/suppression'
    | '/superadmin/clubs/$clubId'
    | '/superadmin/users/$userId'
    | '/_authenticated/admin/'
    | '/_authenticated/profile/'
    | '/superadmin/clubs/'
    | '/_authenticated/admin/users/$userId'
    | '/api/public/hooks/event-reminders'
    | '/api/public/hooks/trial-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DnsCheckRoute: typeof DnsCheckRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LegalKindRoute: typeof LegalKindRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicInquiryRoute: typeof ApiPublicInquiryRoute
  ApiPublicMarketingChatRoute: typeof ApiPublicMarketingChatRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksEventRemindersRoute: typeof ApiPublicHooksEventRemindersRoute
  ApiPublicHooksTrialRemindersRoute: typeof ApiPublicHooksTrialRemindersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-check': {
      id: '/dns-check'
      path: '/dns-check'
      fullPath: '/dns-check'
      preLoaderRoute: typeof DnsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/support': {
      id: '/superadmin/support'
      path: '/support'
      fullPath: '/superadmin/support'
      preLoaderRoute: typeof SuperadminSupportRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/logs': {
      id: '/superadmin/logs'
      path: '/logs'
      fullPath: '/superadmin/logs'
      preLoaderRoute: typeof SuperadminLogsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/billing': {
      id: '/superadmin/billing'
      path: '/billing'
      fullPath: '/superadmin/billing'
      preLoaderRoute: typeof SuperadminBillingRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$kind': {
      id: '/legal/$kind'
      path: '/legal/$kind'
      fullPath: '/legal/$kind'
      preLoaderRoute: typeof LegalKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/superadmin/clubs/': {
      id: '/superadmin/clubs/'
      path: '/clubs'
      fullPath: '/superadmin/clubs/'
      preLoaderRoute: typeof SuperadminClubsIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/superadmin/users/$userId': {
      id: '/superadmin/users/$userId'
      path: '/$userId'
      fullPath: '/superadmin/users/$userId'
      preLoaderRoute: typeof SuperadminUsersUserIdRouteImport
      parentRoute: typeof SuperadminUsersRoute
    }
    '/superadmin/clubs/$clubId': {
      id: '/superadmin/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/superadmin/clubs/$clubId'
      preLoaderRoute: typeof SuperadminClubsClubIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketing-chat': {
      id: '/api/public/marketing-chat'
      path: '/api/public/marketing-chat'
      fullPath: '/api/public/marketing-chat'
      preLoaderRoute: typeof ApiPublicMarketingChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inquiry': {
      id: '/api/public/inquiry'
      path: '/api/public/inquiry'
      fullPath: '/api/public/inquiry'
      preLoaderRoute: typeof ApiPublicInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/profile/privacy': {
      id: '/_authenticated/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof AuthenticatedProfilePrivacyRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/password': {
      id: '/_authenticated/profile/password'
      path: '/password'
      fullPath: '/profile/password'
      preLoaderRoute: typeof AuthenticatedProfilePasswordRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trial-reminders': {
      id: '/api/public/hooks/trial-reminders'
      path: '/api/public/hooks/trial-reminders'
      fullPath: '/api/public/hooks/trial-reminders'
      preLoaderRoute: typeof ApiPublicHooksTrialRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/event-reminders': {
      id: '/api/public/hooks/event-reminders'
      path: '/api/public/hooks/event-reminders'
      fullPath: '/api/public/hooks/event-reminders'
      preLoaderRoute: typeof ApiPublicHooksEventRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfilePasswordRoute: typeof AuthenticatedProfilePasswordRoute
  AuthenticatedProfilePrivacyRoute: typeof AuthenticatedProfilePrivacyRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfilePasswordRoute: AuthenticatedProfilePasswordRoute,
  AuthenticatedProfilePrivacyRoute: AuthenticatedProfilePrivacyRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SuperadminUsersRouteChildren {
  SuperadminUsersUserIdRoute: typeof SuperadminUsersUserIdRoute
}

const SuperadminUsersRouteChildren: SuperadminUsersRouteChildren = {
  SuperadminUsersUserIdRoute: SuperadminUsersUserIdRoute,
}

const SuperadminUsersRouteWithChildren = SuperadminUsersRoute._addFileChildren(
  SuperadminUsersRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminBillingRoute: typeof SuperadminBillingRoute
  SuperadminLogsRoute: typeof SuperadminLogsRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminSupportRoute: typeof SuperadminSupportRoute
  SuperadminUsersRoute: typeof SuperadminUsersRouteWithChildren
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  SuperadminClubsClubIdRoute: typeof SuperadminClubsClubIdRoute
  SuperadminClubsIndexRoute: typeof SuperadminClubsIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminBillingRoute: SuperadminBillingRoute,
  SuperadminLogsRoute: SuperadminLogsRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminSupportRoute: SuperadminSupportRoute,
  SuperadminUsersRoute: SuperadminUsersRouteWithChildren,
  SuperadminIndexRoute: SuperadminIndexRoute,
  SuperadminClubsClubIdRoute: SuperadminClubsClubIdRoute,
  SuperadminClubsIndexRoute: SuperadminClubsIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DnsCheckRoute: DnsCheckRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LegalKindRoute: LegalKindRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicInquiryRoute: ApiPublicInquiryRoute,
  ApiPublicMarketingChatRoute: ApiPublicMarketingChatRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksEventRemindersRoute: ApiPublicHooksEventRemindersRoute,
  ApiPublicHooksTrialRemindersRoute: ApiPublicHooksTrialRemindersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
